server {
    listen 80;
    server_name book.tanxy.net;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name book.tanxy.net;

    root /var/www/book.tanxy.net/site;
    index index.html;

    ssl_certificate     /etc/letsencrypt/live/book.tanxy.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/book.tanxy.net/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    location /api/ {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    gzip on;
    gzip_types text/html text/css application/javascript application/json;

    location ~* \.(css|js|jpg|jpeg|png|svg|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
